//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.10 at 10:46:49 PM IRST 
//


package org.rebecalang.afra.ideplugin.view.modelcheckreport.resultobjectmodel.counterexample.state;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.rebecalang.afra.ideplugin.view.modelcheckreport.resultobjectmodel.counterexample.state package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Res_QNAME = new QName("", "res");
    private final static QName _Pc_QNAME = new QName("", "pc");
    private final static QName _Now_QNAME = new QName("", "now");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.rebecalang.afra.ideplugin.view.modelcheckreport.resultobjectmodel.counterexample.state
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link Variable }
     * 
     */
    public Variable createVariable() {
        return new Variable();
    }

    /**
     * Create an instance of {@link Statevariables }
     * 
     */
    public Statevariables createStatevariables() {
        return new Statevariables();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Rebec }
     * 
     */
    public Rebec createRebec() {
        return new Rebec();
    }

    /**
     * Create an instance of {@link Queue }
     * 
     */
    public Queue createQueue() {
        return new Queue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "res")
    public JAXBElement<String> createRes(String value) {
        return new JAXBElement<String>(_Res_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pc")
    public JAXBElement<String> createPc(String value) {
        return new JAXBElement<String>(_Pc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "now")
    public JAXBElement<String> createNow(String value) {
        return new JAXBElement<String>(_Now_QNAME, String.class, null, value);
    }

}
