//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.04 at 07:25:38 PM IRST 
//


package org.rebecalang.afra.ideplugin.view.modelcheckreport.resultobjectmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}total-spent-time"/>
 *         &lt;element ref="{}reached-states"/>
 *         &lt;element ref="{}reached-transitions"/>
 *         &lt;element ref="{}consumed-mem"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totalSpentTime",
    "reachedStates",
    "reachedTransitions",
    "consumedMem"
})
@XmlRootElement(name = "system-info")
public class SystemInfo {

    @XmlElement(name = "total-spent-time", required = true)
    protected String totalSpentTime;
    @XmlElement(name = "reached-states", required = true)
    protected String reachedStates;
    @XmlElement(name = "reached-transitions", required = true)
    protected String reachedTransitions;
    @XmlElement(name = "consumed-mem", required = true)
    protected String consumedMem;

    /**
     * Gets the value of the totalSpentTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalSpentTime() {
        return totalSpentTime;
    }

    /**
     * Sets the value of the totalSpentTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalSpentTime(String value) {
        this.totalSpentTime = value;
    }

    /**
     * Gets the value of the reachedStates property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReachedStates() {
        return reachedStates;
    }

    /**
     * Sets the value of the reachedStates property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReachedStates(String value) {
        this.reachedStates = value;
    }

    /**
     * Gets the value of the reachedTransitions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReachedTransitions() {
        return reachedTransitions;
    }

    /**
     * Sets the value of the reachedTransitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReachedTransitions(String value) {
        this.reachedTransitions = value;
    }

    /**
     * Gets the value of the consumedMem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumedMem() {
        return consumedMem;
    }

    /**
     * Sets the value of the consumedMem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumedMem(String value) {
        this.consumedMem = value;
    }

}
