//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.27 at 02:16:06 PM IRST 
//


package org.rebecalang.afra.ideplugin.modelcheckreport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "systemInfo",
    "checkedProperty",
    "counterExampleTrace"
})
@XmlRootElement(name = "model-checking-report")
public class ModelCheckingReport {

    @XmlElement(name = "system-info", required = true)
    protected SystemInfo systemInfo;
    @XmlElement(name = "checked-property", required = true)
    protected CheckedProperty checkedProperty;

    @XmlElement(name = "counter-example-trace")
    protected CounterExampleTrace counterExampleTrace;

//    @XmlElement(required = true)
//    protected Options options = null;
    /**
     * Gets the value of the systemInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SystemInfo }
     *     
     */
    public SystemInfo getSystemInfo() {
        return systemInfo;
    }

    /**
     * Sets the value of the systemInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemInfo }
     *     
     */
    public void setSystemInfo(SystemInfo value) {
        this.systemInfo = value;
    }

    /**
     * Gets the value of the checkedProperty property.
     * 
     * @return
     *     possible object is
     *     {@link CheckedProperty }
     *     
     */
    public CheckedProperty getCheckedProperty() {
        return checkedProperty;
    }

    /**
     * Sets the value of the checkedProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckedProperty }
     *     
     */
    public void setCheckedProperty(CheckedProperty value) {
        this.checkedProperty = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link Options }
     *     
     */
   /* public Options getOptions() {
        return options;
    }*/

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link Options }
     *     
     */
  /*  public void setOptions(Options value) {
        this.options = value;
    }*/

    /**
     * Gets the value of the counterExampleTrace property.
     * 
     * @return
     *     possible object is
     *     {@link CounterExampleTrace }
     *     
     */
    public CounterExampleTrace getCounterExampleTrace() {
        return counterExampleTrace;
    }

    /**
     * Sets the value of the counterExampleTrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link CounterExampleTrace }
     *     
     */
    public void setCounterExampleTrace(CounterExampleTrace value) {
        this.counterExampleTrace = value;
    }

}
