//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.27 at 02:16:06 PM IRST 
//


package org.rebecalang.afra.ideplugin.modelcheckreport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "queue",
    "stateVars"
})
@XmlRootElement(name = "rebec")
public class Rebec {

    @XmlAttribute(name = "reactive-class", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String reactiveClass;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlElement(required = true)
    protected Queue queue;
    @XmlElement(name = "state-vars", required = true)
    protected StateVars stateVars;

    /**
     * Gets the value of the reactiveClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReactiveClass() {
        return reactiveClass;
    }

    /**
     * Sets the value of the reactiveClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReactiveClass(String value) {
        this.reactiveClass = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the queue property.
     * 
     * @return
     *     possible object is
     *     {@link Queue }
     *     
     */
    public Queue getQueue() {
        return queue;
    }

    /**
     * Sets the value of the queue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Queue }
     *     
     */
    public void setQueue(Queue value) {
        this.queue = value;
    }

    /**
     * Gets the value of the stateVars property.
     * 
     * @return
     *     possible object is
     *     {@link StateVars }
     *     
     */
    public StateVars getStateVars() {
        return stateVars;
    }

    /**
     * Sets the value of the stateVars property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateVars }
     *     
     */
    public void setStateVars(StateVars value) {
        this.stateVars = value;
    }

}
