//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.27 at 02:16:06 PM IRST 
//


package org.rebecalang.afra.ideplugin.modelcheckreport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totalSpentTime",
    "maxDepth",
    "hashtableSize",
    "reachedStates",
    "reachedTransitions",
    "consumedMem"
})
@XmlRootElement(name = "system-info")
public class SystemInfo {

    @XmlElement(name = "total-spent-time", required = true)
    protected String totalSpentTime;
    @XmlElement(name = "max-depth", required = false)
    protected String maxDepth;
    @XmlElement(name = "hashtable-size", required = false)
    protected String hashtableSize;
    @XmlElement(name = "reached-states", required = true)
    protected String reachedStates;
    @XmlElement(name = "reached-transitions", required = true)
    protected String reachedTransitions;
    @XmlElement(name = "consumed-mem", required = true)
    protected String consumedMem;

    /**
     * Gets the value of the totalSpentTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalSpentTime() {
        return totalSpentTime;
    }

    /**
     * Sets the value of the totalSpentTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalSpentTime(String value) {
        this.totalSpentTime = value;
    }

    /**
     * Gets the value of the maxDepth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxDepth() {
    	if (maxDepth == null)
    		return "100000";
    	return maxDepth;
    }

    /**
     * Sets the value of the maxDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxDepth(String value) {
        this.maxDepth = value;
    }

    /**
     * Gets the value of the hashtableSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHashtableSize() {
    	if(hashtableSize == null)
    		return "20";
    	return hashtableSize;
    }

    /**
     * Sets the value of the hashtableSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHashtableSize(String value) {
        this.hashtableSize = value;
    }

    /**
     * Gets the value of the reachedStates property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReachedStates() {
        return reachedStates;
    }

    /**
     * Sets the value of the reachedStates property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReachedStates(String value) {
        this.reachedStates = value;
    }

    /**
     * Gets the value of the reachedTransitions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReachedTransitions() {
        return reachedTransitions;
    }

    /**
     * Sets the value of the reachedTransitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReachedTransitions(String value) {
        this.reachedTransitions = value;
    }

    /**
     * Gets the value of the consumedMem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumedMem() {
        return consumedMem;
    }

    /**
     * Sets the value of the consumedMem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumedMem(String value) {
        this.consumedMem = value;
    }

}
