//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.28 at 01:56:46 PM IRST 
//


package org.rebecalang.afra.ideplugin.view.modelcheckreport.resultobjectmodel.counterexample.analysisresult;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}system-info"/>
 *         &lt;element ref="{}checked-property"/>
 *         &lt;element ref="{}extra-details" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "systemInfo",
    "checkedProperty",
    "extraDetails"
})
@XmlRootElement(name = "model-checking-report")
public class ModelCheckingReport {

    @XmlElement(name = "system-info", required = true)
    protected SystemInfo systemInfo;
    @XmlElement(name = "checked-property", required = true)
    protected CheckedProperty checkedProperty;
    @XmlElement(name = "extra-details")
    protected ExtraDetails extraDetails;

    /**
     * Gets the value of the systemInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SystemInfo }
     *     
     */
    public SystemInfo getSystemInfo() {
        return systemInfo;
    }

    /**
     * Sets the value of the systemInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemInfo }
     *     
     */
    public void setSystemInfo(SystemInfo value) {
        this.systemInfo = value;
    }

    /**
     * Gets the value of the checkedProperty property.
     * 
     * @return
     *     possible object is
     *     {@link CheckedProperty }
     *     
     */
    public CheckedProperty getCheckedProperty() {
        return checkedProperty;
    }

    /**
     * Sets the value of the checkedProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckedProperty }
     *     
     */
    public void setCheckedProperty(CheckedProperty value) {
        this.checkedProperty = value;
    }

    /**
     * Gets the value of the extraDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ExtraDetails }
     *     
     */
    public ExtraDetails getExtraDetails() {
        return extraDetails;
    }

    /**
     * Sets the value of the extraDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtraDetails }
     *     
     */
    public void setExtraDetails(ExtraDetails value) {
        this.extraDetails = value;
    }

}
