//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.28 at 01:56:46 PM IRST 
//


package org.rebecalang.afra.ideplugin.view.modelcheckreport.resultobjectmodel.counterexample.analysisresult;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="total-spent-time" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="reached-states" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="reached-transitions" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="consumed-mem" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totalSpentTime",
    "reachedStates",
    "reachedTransitions",
    "consumedMem"
})
@XmlRootElement(name = "system-info")
public class SystemInfo {

    @XmlElement(name = "total-spent-time", required = true)
    protected BigDecimal totalSpentTime;
    @XmlElement(name = "reached-states", required = true)
    protected BigDecimal reachedStates;
    @XmlElement(name = "reached-transitions", required = true)
    protected BigDecimal reachedTransitions;
    @XmlElement(name = "consumed-mem", required = true)
    protected BigDecimal consumedMem;

    /**
     * Gets the value of the totalSpentTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalSpentTime() {
        return totalSpentTime;
    }

    /**
     * Sets the value of the totalSpentTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalSpentTime(BigDecimal value) {
        this.totalSpentTime = value;
    }

    /**
     * Gets the value of the reachedStates property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReachedStates() {
        return reachedStates;
    }

    /**
     * Sets the value of the reachedStates property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReachedStates(BigDecimal value) {
        this.reachedStates = value;
    }

    /**
     * Gets the value of the reachedTransitions property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReachedTransitions() {
        return reachedTransitions;
    }

    /**
     * Sets the value of the reachedTransitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReachedTransitions(BigDecimal value) {
        this.reachedTransitions = value;
    }

    /**
     * Gets the value of the consumedMem property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getConsumedMem() {
        return consumedMem;
    }

    /**
     * Sets the value of the consumedMem property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setConsumedMem(BigDecimal value) {
        this.consumedMem = value;
    }

}
