version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point

    working_directory: ~/afra # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:10-jdk # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: afra

      - run: wget https://raw.githubusercontent.com/rebeca-lang/org.rebecalang.rmc/master/target/rmc-2.7.5.jar
      - run: mvn -N install:install-file -Dfile=rmc-2.7.5.jar -DgroupId=org.rebecalang -DartifactId=rmc -Dversion=2.7.5 -Dpackaging=jar
      - run: wget https://raw.githubusercontent.com/rebeca-lang/org.rebecalang.modeltransformer/master/target/modeltransformer-1.3.0.jar
      - run: mvn -N install:install-file -Dfile=modeltransformer-1.3.0.jar -DgroupId=org.rebecalang -DartifactId=modeltransformer -Dversion=1.3.0 -Dpackaging=jar
      - run: wget https://raw.githubusercontent.com/rebeca-lang/org.rebecalang.statespacetransformer/master/target/statespacetransformer-1.0.0.jar
      - run: mvn -N install:install-file -Dfile=statespacetransformer-1.0.0.jar -DgroupId=org.rebecalang -DartifactId=statespacetransformer -Dversion=1.0.0 -Dpackaging=jar
      #- run: mvn dependency:go-offline # gets the project dependencies

      - run: mvn install # run the actual tests

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: afra

      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard. 
          path: target/surefire-reports

      - store_artifacts: # store the uberjar as an artifact
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples    
