//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.27 at 02:16:06 PM IRST 
//


package org.rebecalang.ide.afra.modelcheckreport;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "systemState"
})
@XmlRootElement(name = "counter-example-trace")
public class CounterExampleTrace {

    @XmlElement(name = "system-state", required = true)
    protected List<SystemState> systemState;

    /**
     * Gets the value of the systemState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systemState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystemState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SystemState }
     * 
     * 
     */
    public List<SystemState> getSystemState() {
        if (systemState == null) {
            systemState = new ArrayList<SystemState>();
        }
        return this.systemState;
    }

}
