//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.27 at 02:16:06 PM IRST 
//


package org.rebecalang.ide.afra.modelcheckreport;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.rebecalang.afra.modelcheckreport package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.rebecalang.afra.modelcheckreport
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CounterExampleTrace }
     * 
     */
    public CounterExampleTrace createCounterExampleTrace() {
        return new CounterExampleTrace();
    }

    /**
     * Create an instance of {@link ModelCheckingReport }
     * 
     */
    public ModelCheckingReport createModelCheckingReport() {
        return new ModelCheckingReport();
    }

    /**
     * Create an instance of {@link CheckedProperty }
     * 
     */
    public CheckedProperty createCheckedProperty() {
        return new CheckedProperty();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link ExecutingRebec }
     * 
     */
    public ExecutingRebec createExecutingRebec() {
        return new ExecutingRebec();
    }

    /**
     * Create an instance of {@link Option }
     * 
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link SystemState }
     * 
     */
    public SystemState createSystemState() {
        return new SystemState();
    }

    /**
     * Create an instance of {@link Queue }
     * 
     */
    public Queue createQueue() {
        return new Queue();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link Rebec }
     * 
     */
    public Rebec createRebec() {
        return new Rebec();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link Options }
     * 
     */
    public Options createOptions() {
        return new Options();
    }

    /**
     * Create an instance of {@link SystemInfo }
     * 
     */
    public SystemInfo createSystemInfo() {
        return new SystemInfo();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link StateVar }
     * 
     */
    public StateVar createStateVar() {
        return new StateVar();
    }

    /**
     * Create an instance of {@link GlobalVars }
     * 
     */
    public GlobalVars createGlobalVars() {
        return new GlobalVars();
    }

    /**
     * Create an instance of {@link StateVars }
     * 
     */
    public StateVars createStateVars() {
        return new StateVars();
    }

}
