//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.27 at 02:16:06 PM IRST 
//


package org.rebecalang.ide.afra.modelcheckreport;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rebec",
    "globalVars",
    "executingRebec",
    "nextSystemState",
    "fairnessCounter",
    "claimState"
})
@XmlRootElement(name = "system-state")
public class SystemState {

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String id;
    @XmlElement(required = true)
    protected List<Rebec> rebec;
    @XmlElement(name = "global-vars", required = true)
    protected GlobalVars globalVars;
    @XmlElement(name = "executing-rebec", required = true)
    protected ExecutingRebec executingRebec;
    @XmlElement(name = "next-system-state", required = true)
    protected String nextSystemState;
    @XmlElement(name = "fairness-counter", required = true)
    protected String fairnessCounter;
    @XmlElement(name = "claim-state", required = true)
    protected String claimState;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the rebec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rebec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRebec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rebec }
     * 
     * 
     */
    public List<Rebec> getRebec() {
        if (rebec == null) {
            rebec = new ArrayList<Rebec>();
        }
        return this.rebec;
    }

    /**
     * Gets the value of the globalVars property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalVars }
     *     
     */
    public GlobalVars getGlobalVars() {
        return globalVars;
    }

    /**
     * Sets the value of the globalVars property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalVars }
     *     
     */
    public void setGlobalVars(GlobalVars value) {
        this.globalVars = value;
    }

    /**
     * Gets the value of the executingRebec property.
     * 
     * @return
     *     possible object is
     *     {@link ExecutingRebec }
     *     
     */
    public ExecutingRebec getExecutingRebec() {
        return executingRebec;
    }

    /**
     * Sets the value of the executingRebec property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecutingRebec }
     *     
     */
    public void setExecutingRebec(ExecutingRebec value) {
        this.executingRebec = value;
    }

    /**
     * Gets the value of the nextSystemState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextSystemState() {
        return nextSystemState;
    }

    /**
     * Sets the value of the nextSystemState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextSystemState(String value) {
        this.nextSystemState = value;
    }

    /**
     * Gets the value of the fairnessCounter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFairnessCounter() {
        return fairnessCounter;
    }

    /**
     * Sets the value of the fairnessCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFairnessCounter(String value) {
        this.fairnessCounter = value;
    }

    /**
     * Gets the value of the claimState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimState() {
        return claimState;
    }

    /**
     * Sets the value of the claimState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimState(String value) {
        this.claimState = value;
    }

}
