//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.04 at 07:25:38 PM IRST 
//


package org.rebecalang.afra.ideplugin.view.modelcheckreport.resultobjectmodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.rebecalang.afra.ideplugin.view.modelcheckreport.resultobjectmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Result_QNAME = new QName("", "result");
    private final static QName _ReachedTransitions_QNAME = new QName("", "reached-transitions");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _ReachedStates_QNAME = new QName("", "reached-states");
    private final static QName _ConsumedMem_QNAME = new QName("", "consumed-mem");
    private final static QName _Type_QNAME = new QName("", "type");
    private final static QName _Option_QNAME = new QName("", "option");
    private final static QName _TotalSpentTime_QNAME = new QName("", "total-spent-time");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.rebecalang.afra.ideplugin.view.modelcheckreport.resultobjectmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Options }
     * 
     */
    public Options createOptions() {
        return new Options();
    }

    /**
     * Create an instance of {@link CheckedProperty }
     * 
     */
    public CheckedProperty createCheckedProperty() {
        return new CheckedProperty();
    }

    /**
     * Create an instance of {@link ModelCheckingReport }
     * 
     */
    public ModelCheckingReport createModelCheckingReport() {
        return new ModelCheckingReport();
    }

    /**
     * Create an instance of {@link SystemInfo }
     * 
     */
    public SystemInfo createSystemInfo() {
        return new SystemInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "result")
    public JAXBElement<String> createResult(String value) {
        return new JAXBElement<String>(_Result_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reached-transitions")
    public JAXBElement<String> createReachedTransitions(String value) {
        return new JAXBElement<String>(_ReachedTransitions_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reached-states")
    public JAXBElement<String> createReachedStates(String value) {
        return new JAXBElement<String>(_ReachedStates_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "consumed-mem")
    public JAXBElement<String> createConsumedMem(String value) {
        return new JAXBElement<String>(_ConsumedMem_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "option")
    public JAXBElement<String> createOption(String value) {
        return new JAXBElement<String>(_Option_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "total-spent-time")
    public JAXBElement<String> createTotalSpentTime(String value) {
        return new JAXBElement<String>(_TotalSpentTime_QNAME, String.class, null, value);
    }

}
